name: Deploy static site to Azure VM

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.AZURE_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: ./
          target: /home/${{ secrets.AZURE_USER }}/temp

      - name: Execute remote SSH commands (promote to /usr/site)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            sudo mkdir -p /usr/site
            sudo cp -r /home/${{ secrets.AZURE_USER }}/temp/* /usr/site/
            sudo chown -R www-data:www-data /usr/site
            sudo rm -rf /home/${{ secrets.AZURE_USER }}/temp
            sudo nginx -t && sudo systemctl reload nginx

